# Generated by Django 4.1.1 on 2022-10-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Макс. 32 символов', max_length=32, verbose_name='название')),
                ('is_published', models.BooleanField(default=False, verbose_name='публикация')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категория',
                'db_table': 'catalogue_categories',
                'ordering': ('id',),
            },
        ),
    ]
