# Generated by Django 4.1.1 on 2022-10-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Максю 32 символа', max_length=32, verbose_name='наименование')),
                ('is_published', models.BooleanField(default=False, verbose_name='публикация')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.category', verbose_name='род. категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегория',
                'db_table': 'catalogue_subcategories',
                'ordering': ('category', 'id'),
            },
        ),
    ]
